package citizenmanagementplataform;

public enum states {
    START, SELECTEDJUSTMIN, SELECTINGPROCEDURES, SELECTINGCRIMINALREPORTCERTF, SELECTINGAUTHMETHOD, ENTERNIFANDPIN, ENTERPIN,
    ENTERFORM, REALIZINGPAYMENT, ENTERCARDDATA, OBTAININGCERTIFICATE, PRINTINGDOCUMENT, END;
}
